# Generated by Django 4.2.2 on 2023-06-27 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='colour',
            field=models.ManyToManyField(to='products.colour_varient'),
        ),
        migrations.AlterField(
            model_name='products',
            name='size',
            field=models.ManyToManyField(to='products.size_varient'),
        ),
    ]
