# Generated by Django 4.2.2 on 2023-06-27 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_products_colour_alter_products_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='colour',
            field=models.ManyToManyField(blank=True, to='products.colour_varient'),
        ),
        migrations.AlterField(
            model_name='products',
            name='size',
            field=models.ManyToManyField(blank=True, to='products.size_varient'),
        ),
    ]
