# Generated by Django 4.2.2 on 2023-07-03 14:03

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_products_colour_alter_products_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='product_name'),
        ),
    ]
